name: crop_screenshot
description: Crop and save special screenshots automatically.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  screenshot: ^1.3.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  path_provider: ^2.0.14
  gal: ^2.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

