name: screenshot_cropper
description: A simple app to crop screenshots after double-pressing the side button.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  gal: ^1.3.0 # для работы с изображениями и сохранения в галерею
  intl: ^0.18.0 # для мультиязычности
  path_provider: ^2.0.15 # чтобы работать с временными файлами
  image: ^4.0.17 # для обрезки скриншота

flutter:
  uses-material-design: true
